version: 2
updates:
# https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/examples/complete"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/test/src"
    schedule:
      interval: "daily"
